apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  namespace: pipelines
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: $GIT_REPO_USERNAME
  password: $GIT_REPO_PASSWORD

