apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: pipelines
  annotations:
    tekton.dev/docker-0: https://repo-harbor.apps.okd.nicknach.net
type: kubernetes.io/basic-auth
stringData:
  username: $IMAGE_REPO_USERNAME
  password: $IMAGE_REPO_PASSWORD

